---
apiVersion: v1
kind: Service
metadata:
  name: qso-mapper
  namespace: default
  labels:
    app: qso-mapper
spec:
  type: ClusterIP
  selector:
    app: qso-mapper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
